export const PRIMARY_LOCATION = 'PRIMARY'
export const SECONDARY_LOCATION = 'SECONDARY'
export const THIRD_LOCATION = 'THIRD'
export const FOURTH_LOCATION = 'FOURTH'
export const FIFTH_LOCATION = 'FIFTH'
export const FEATURE_LOCATION = 'FEATURE'
export const FOOTER_LOCATION = 'FOOTER'
export const RCA_LOCATION = 'RCA'
